### ISSUE TITLE
Always returning "true" on Comprehend

### ISSUE THREAD

**Issue by CoreyH** [Deviated-Systems/SpamSpy-Tracker#2] opened 2023-03-16 10:30 UTC
No matter what text I put into the request on /comprehend I get a value of True returned.

**Comment by Yeehawlerz101** [comment] 2023-03-17 23:33
Hey there @CoreyH! Thank you for bringing this issue to our attention. We apologize for the inconvenience caused by the incorrect comprehension results. We're constantly improving the SpamSpy modal and would like you to help us by kindly asking you to use the learn command to have the incorrectly marked content be sent for proper training. This will allow us to identify, correct, and retrain the model for errors. We greatly appreciate your cooperation and feedback. Thank you. Additionally, we're planning a large update to the modal soon (2ish weeks out) where there will be more conversational data added. I'll leave this issue open until we apply the updates 😄.

**Comment by canadaka** [comment] 2023-04-07 05:19
I started using the API this evening and all my results have been returning TRUE as well. I had to disable any real use for now and I'm only logging the responses.

Sample:
```
Heading downhill from the road, the trail is in good condition. However when you get to the bottom, there are long pools that would be best to dismount to walk through.
```

**Comment by Yeehawlerz101** [comment] 2023-04-07 14:21
> I started using the API this evening and all my results have been returning TRUE as well. I had to disable any real use for now and I'm only logging the responses.
> 
> Sample:
> 
> ```
> Heading downhill from the road, the trail is in good condition. However when you get to the bottom, there are long pools that would be best to dismount to walk through.
> ```
> 
> I was also getting a bunch of "{"message":"400, bad request"}" responses. This seems to be from weird characters in the text like `•` so I've stripped out a bunch of characters before sending now.
> 
> However I'm still getting an error 400 on some like the following. The API docs don't really mention the limitations on what text can be sent.
> 
> ```
> MUTUBA SEED 0731878687 PENIS ENLARGEMENT CREAM IN CENTURION,LYTTELTON,DIE HOEWES,OLIEVENHOUTBOSCH,LAUDIUM,ATTERIDGEVILLE,LOTUS,SAULSVILLE Mutuba Alpha 4 in 1 combo Penis Enlargement Pills and cream call Dr Mich 27731878687,You can watsup Mutuba Alpha 4 in 1 Enhancements introduces the new and strongest penis enlargements pills and cream on market, when you start using these products , you will have to see a great sex change in just 3 days and in just 7 days, you will be having our permanent results and stated below,  Multiple Male Orgasms  Harder Erections  Satisfying Your Partner  A More Vascular Look  Increased Ejaculations  Staying Erect after Orgasm  Meditation and Visualization Another major difference is how people will treat you. Your lover will get a new spark of excitement when it comes to sex. You will start to get the jealous looks in the locker room. You will feel better about yourself on many different levels. You will be more confident in the bedroom, which will equate to more confidence in your day-to-day life. No more hiding in the dark, or covering up after sex. You will proudly display the new you with an unbelievable confidence. Feeling too small or inadequate in the penis department is one of the biggest problems men suffer with mentally. After a few short weeks using my Penis Enlargement Herbs these old feelings will start to fade and will be replaced by a new you that you never dreamed possible. Mutuba Alpha 4 in 1 combo plus Penis enlargement pills and cream has helped men change their relationships and reach otherwise unattainable goals. They reach a point of happiness that was never thought possible before. Your life will change once you embark on this wonderful Penis Enlargement journey. You will feel and see these changes in every part of your life. All these products are extracted from Local herbs, Mutuba trees seeds from Sudan and Congo forests and approved by the Mutuba enhancements in South Africa, All our products are tested and approved and they have got no any side effect to any human, Ready for use, Mutuba Enhancements have other products for both male and female, Stretch marks removal gel, weight gaining and loss pills for both male and female, Vagina tightening pills and cream, Tummy cutters, skin lightening products, spots removal, Hips,Bums,Thighs and Breasts enhancements and more. for order call 27731878687 or Whatsapp
> ```

Hi there canadaka! If your data is only returning true, please use the Learn command. This will allow us to review the contents manually for now. There is also a planned discord bot to vote as a community for spam. For now, the text content only supports ASCII (for now)  [ASCII Table - GeeksforGeeks](https://www.geeksforgeeks.org/ascii-table/#). We intend to have a 'stripper/cleanup' step that would remove invalid / breaking characters from the content. Lastly, internally we recently found an issue with large data strings being passed into SpamSpy and the text will be concatenated automatically, which will break the API call returning the 400 error. In our testing, it has been between 512 and 1024 character lengths. I hope this answers your questions!

Side Note: eventually we intend to have larger support for languages (i.e.: Spanish, French {À/È/Î/Ü}) once we feel like the English training data is 75% complete

**Comment by CoreyH** [comment] 2023-04-08 07:34
One MAJOR update here. The true/false seems to be reversed from what I expected. (please confirm)

True means the message has been validated as not-spam
False identifies a potential spammy message.

**Comment by JasonCheroske** [comment] 2023-10-19 21:23
Hi @CoreyH and @canadaka,

Firstly, our sincere apologies for the delay in our response. We've been deeply engrossed in addressing the issues with v2 and wanted to ensure we had concrete answers before reaching out.

The challenges with SpamSpy V1, as you've experienced, largely stemmed from its sensitivity to content. Over time, we've tried numerous approaches to rectify this. The core issue was the lack of "ham" content in our training data, especially content with poor English, foreign character sets, and other nuances. We developed tools to clean up the text and assist the AI in making better decisions. While we saw improved results in the V2 snapshot, it still wasn't up to our desired standard. As you both might be aware, maintaining SpamSpy V1 while ironing out the kinks in v2 has been a significant challenge.

To address these challenges, we've come up with the `mode` header in our internal API branches. This feature aims to enhance the model's capabilities and provide a more robust user experience. It currently has three parameters: `"Resubmit", "submit", and "Contextualized"`. The "contextualized" mode, in particular, allows for more nuanced submissions, letting you submit a JSON object with a "target-content" field and additional context keys. This approach enables more detailed submissions:
```ts
header: { "mode": "Contextualized" },
body : {
  "email": "spam@scam.com",
  "sender": "John Doe",
  "subject": "Totally Not Spam",
  "target-content": "Click this link to claim your $1,000,000 prize!",
}
//or 
header: { "target-content": "email-body", "mode": "Contextualized" },
body : {//Lead Form Example
  "email-address": "spam@scam.com",
  "email-sender-name": "John Doe",
  "email-subject": "Totally Not Spam",
  "email-body": "Click this link to claim your $1,000,000 prize!" 
}
```

However, this feature is still in its infancy, and we'd need a substantial amount of data (>= 10,000 records) to begin training a model effectively. To move in the right direction, we're considering allowing a simple "context" field submission, allowing say an entire chat log, containing your targeted content. By analyzing the submitted content with and without context, we can make more informed predictions.

For more details on the deprecation of v1, please refer to our [news update](https://spamspy.io/News/Spamspy-V1-EoL). While V2 is showing promise, it still doesn't meet our stringent standards. Our commitment to ensuring the community retains control and influence over responses has been a guiding principle in our journey this year. The best way to assist us, and in turn, benefit from SpamSpy's enhanced capabilities, would be to submit content. This will also help SpamSpy better handle the content submitted to your domains and lead funnels once content comprehension is back online.

The V2 Alpha Snapshot uses the old auth systems, yet in a stroke of luck our team has been able to partially restore function, except the comprehend endpoint, which is currently unavailable.

Lastly, we'd be honored if you joined our [discord](https://discord.gg/nDw5HbKt). Given that both of you are foundational members of our community, your insights and feedback on V2's features would be invaluable.

Thank you for your patience and understanding. We're committed to delivering a product that meets and exceeds expectations.

**Closed by JasonCheroske** 2023-10-19 21:23 UTC
